version: "3.9"
services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=tpcc
    volumes:
      - db-data:/var/lib/mysql
  app:
    build:
      context: app
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/tpcc
      - DATABASE_USER=root
      - DATABASE_PASSWORD=${DB_PASSWORD}

volumes:
  db-data:
